
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 30 22:45:00 BRT 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class SymbolCodes {
  /* terminals */
  public static final int MOD = 16;
  public static final int MENOS = 13;
  public static final int PTVIRG = 18;
  public static final int IDENT = 11;
  public static final int KW_FINAL = 9;
  public static final int KW_IF = 4;
  public static final int PONTO = 20;
  public static final int ABREPAR = 22;
  public static final int OP_RELACIONAL = 21;
  public static final int INTEIRO = 28;
  public static final int ATRIB = 17;
  public static final int FECHACOL = 25;
  public static final int KW_CLASS = 3;
  public static final int MAIS = 12;
  public static final int ABRECHAVE = 26;
  public static final int EOF = 0;
  public static final int MULT = 14;
  public static final int VIRG = 19;
  public static final int KW_WHILE = 6;
  public static final int KW_NEW = 10;
  public static final int DIV = 15;
  public static final int error = 1;
  public static final int FECHACHAVE = 27;
  public static final int KW_VOID = 8;
  public static final int FECHAPAR = 23;
  public static final int KW_PROGRAM = 2;
  public static final int KW_READ = 7;
  public static final int ABRECOL = 24;
  public static final int KW_ELSE = 5;
}

